language: node_js
node_js:
  - "6"
  - "stable"

before_install:
  - npm install -g istanbul mocha codeclimate-test-reporter

after_success:
  - pwd
  - istanbul cover _mocha -- -R spec ./test/*.js
  - codeclimate < ./coverage/lcov.info